FROM python:3.10.7-slim-buster

EXPOSE 5050

ENV APP /app

WORKDIR ${APP}

ADD requirements.txt .
RUN pip3 install -r requirements.txt

COPY . .
RUN mkdir /file_storage

CMD ["flask", "run", "--host", "0.0.0.0", "--port", "5050"]