FROM python:3.10.7-slim-buster

EXPOSE 5060

ENV APP /app

WORKDIR ${APP}

RUN apt-get update -y \
    && apt-get -y install \
    git \
    build-essential=12.6 \
    libglib2.0-0=2.58.3-2+deb10u3 \
    libsm6=2:1.2.3-1 \
    libxext6=2:1.3.3-1+b2 \
    libxrender-dev=1:0.9.10-1 \
    libgl1-mesa-dev=18.3.6-2+deb10u1 \
    && rm -rf /var/lib/apt/lists/*

# Needs apt-get update again to execute
RUN apt-get update -y \
    && apt-get -y install \
    libtesseract-dev \
    poppler-utils \
    tesseract-ocr

RUN pip3 install torch torchvision

RUN pip3 install 'git+https://github.com/facebookresearch/fvcore'
RUN pip3 install 'git+https://github.com/facebookresearch/detectron2.git@v0.1.3#egg=detectron2'

# Detectron2 install overwrites fvcore library
RUN pip3 install 'git+https://github.com/facebookresearch/fvcore'
RUN pip3 install 'git+https://github.com/facebookresearch/iopath'

RUN pip3 install cython pycocotools Flask-SocketIO

ADD requirements.txt .
RUN pip3 install -r requirements.txt

COPY .. .
RUN mkdir /file_storage
CMD ["python3", "app.py"]
